from .public_views import *  
from .admin_views import *
from .advisory_teacher_views import *
from .non_advisory_teacher_views import *
from .principal_views import *
from .registrar_views import *
from .face_recognition_views import *
from .message_views import *
from .chatbot_views import *
from .user_settings_views import *
