# Generated by Django 5.2.1 on 2025-05-25 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PROTECHAPP', '0002_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_new',
            field=models.BooleanField(default=True),
        ),
    ]
