# Generated by Django 5.2.1 on 2025-05-28 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PROTECHAPP', '0004_remove_customuser_status_alter_customuser_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='guardian',
            name='relationship',
            field=models.CharField(choices=[('FATHER', 'Father'), ('MOTHER', 'Mother'), ('GUARDIAN', 'Guardian'), ('OTHER', 'Other')], default='OTHER', max_length=50),
        ),
    ]
