# Generated by Django 5.2.1 on 2025-05-28 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PROTECHAPP', '0005_guardian_relationship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guardian',
            name='relationship',
            field=models.CharField(max_length=50),
        ),
    ]
