# Generated by Django 4.2.7 on 2025-11-23 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PROTECHAPP', '0007_alter_attendance_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('otp_code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('ip_address', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'verbose_name': 'Password Reset OTP',
                'verbose_name_plural': 'Password Reset OTPs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='attendance_mode',
            field=models.CharField(choices=[('SEPARATE', 'Separate (Time In & Time Out on different screens)'), ('HYBRID', 'Hybrid (Time In & Time Out on same screen)')], default='SEPARATE', help_text='Select whether attendance devices show separate or combined time in/out screens', max_length=20),
        ),
    ]
