# Generated by Django 4.2.7 on 2025-11-23 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PROTECHAPP', '0009_add_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='late_time_cutoff',
            field=models.TimeField(default='08:00:00', help_text='Time cutoff for late arrival (stored in UTC, displayed in Asia/Manila)'),
        ),
    ]
