# Generated by Django 5.2.6 on 2025-12-01 08:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PROTECHAPP', '0010_systemsettings_late_time_cutoff'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backup_type', models.CharField(choices=[('MANUAL', 'Manual'), ('AUTOMATIC', 'Automatic')], help_text='Type of backup: Manual or Automatic', max_length=20)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed')], help_text='Status of backup operation', max_length=20)),
                ('filename', models.CharField(help_text='Name of the backup file', max_length=255)),
                ('filepath', models.CharField(help_text='Full path to the backup file', max_length=500)),
                ('file_size_bytes', models.BigIntegerField(help_text='Size of backup file in bytes')),
                ('file_size_mb', models.DecimalField(decimal_places=2, help_text='Size in MB', max_digits=10)),
                ('error_message', models.TextField(blank=True, help_text='Error message if backup failed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the backup was created')),
                ('initiated_by', models.ForeignKey(blank=True, help_text='User who initiated manual backup (null for automatic)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Backup Log',
                'verbose_name_plural': 'Backup Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
