# Generated by Django 4.2.7 on 2026-01-12 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PROTECHAPP', '0012_calendarevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='email_notifications_enabled',
            field=models.BooleanField(default=True, help_text='Enable or disable email notifications for attendance'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='sms_notifications_enabled',
            field=models.BooleanField(default=True, help_text='Enable or disable SMS notifications for attendance'),
        ),
    ]
