# Generated by Django 4.2.7 on 2026-01-12 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PROTECHAPP', '0013_systemsettings_email_notifications_enabled_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemsettings',
            name='late_time_cutoff',
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='first_class_start_time',
            field=models.TimeField(default='08:00:00', help_text='Time when the first class session begins (stored in UTC, displayed in Asia/Manila)'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='grace_period_minutes',
            field=models.IntegerField(default=5, help_text='Grace period in minutes after class start time before marking as late'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='second_class_start_time',
            field=models.TimeField(blank=True, help_text='Optional: Time when the second class session begins (must be at least 4 hours after first class)', null=True),
        ),
    ]
