# Generated by Django 4.2.7 on 2026-01-12 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PROTECHAPP', '0014_remove_systemsettings_late_time_cutoff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsettings',
            name='first_class_start_time',
            field=models.TimeField(default='07:00:00', help_text='Time when the first class session begins (stored in UTC, displayed in Asia/Manila)'),
        ),
    ]
