# Generated by Django 4.2.7 on 2026-01-12 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PROTECHAPP', '0015_alter_systemsettings_first_class_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='recognition_display_mode',
            field=models.CharField(choices=[('SCROLLABLE', 'Scrollable List - Show all recognized students'), ('LATEST', 'Latest Only - Show only the most recent student')], default='SCROLLABLE', help_text='Control how recognized students are displayed on Time In/Out screens', max_length=20),
        ),
    ]
