# Generated by Django 5.2.6 on 2026-01-12 14:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PROTECHAPP', '0016_systemsettings_recognition_display_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnauthorizedLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_path', models.CharField(help_text='Path to the unauthorized face photo', max_length=500)),
                ('camera_name', models.CharField(help_text='Name of the camera that captured the photo', max_length=100)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, help_text='When the unauthorized face was detected')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Unauthorized Log',
                'verbose_name_plural': 'Unauthorized Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
