# Generated by Django 5.2.6 on 2026-01-12 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PROTECHAPP', '0017_unauthorizedlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='spoof_proof_enabled',
            field=models.BooleanField(default=True, help_text='Require facial micro-movements (blink/landmark motion) to block photo/video spoofs'),
        ),
    ]
