# Generated by Django 4.2.7 on 2026-01-12 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PROTECHAPP', '0019_systemsettings_gate_mode_remove_attendance_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='prototype_gate_system_enabled',
            field=models.BooleanField(default=True, help_text='Enable or disable the prototype gate system and gate queue check functionality'),
        ),
    ]
