# Generated by Django 4.2.7 on 2026-02-05 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PROTECHAPP', '0020_systemsettings_prototype_gate_system_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='holiday_mode',
            field=models.BooleanField(default=False, help_text='When enabled, face recognition attendance is disabled on all devices (Time In, Time Out, Hybrid)'),
        ),
    ]
