# Generated by Django 4.2.7 on 2026-02-07 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PROTECHAPP', '0021_systemsettings_holiday_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='camera_count',
            field=models.IntegerField(choices=[(1, '1 Camera'), (2, '2 Cameras'), (3, '3 Cameras'), (4, '4 Cameras')], default=1, help_text='Number of cameras to display in Separate Screens mode (1-4)'),
        ),
    ]
